package codeoperations;

/**
 * Created by mb on 17/04/2017.
 */
public enum Statement {
    PRINT, PRINT_LINE, CLASS, MAIN, WHILE, FOR, IF, STRING, VALUE, NEW_LINE, METHOD_NAME, CLASS_NAME,
    BACK, NEXT, BACKSPACE, LINE_UP, LINE_DOWN, UNDO, RUN_PROGRAM, CLOSE_FILE, SAVE_FILE,
    NEXT_FILE, PREV_FILE, OPEN_FILE, NEW_FILE, OPEN_HELP, CHAR
}
